spring:
  redis:
    database: 0
    host: 112.74.161.0
    port: 6379
    password: 123456
  datasource:
    username: root
    password: root
    url: jdbc:mysql://112.74.161.0:3306/ic_database?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com/petrichor/system/entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenHeader: Authorization
  secret: security-secret
  expiration: 604800
  tokenHead: 'Bearer '
secure:
  ignored:
    urls:
      - /system/*
      - /doc.html
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**